### PR TITLE
Added most important things to the README.

### PR DESCRIPTION
**Pull request by mgoral**

### CODE REVIEW

**Comment by mgoral** [comment]
So? What about this PR?

**Comment by robin92** [comment]
Can't merge pull request due to not fast-forward. Please rebase/merge (update) the PR.

**Comment by mgoral** [comment]
I clicked "update branch", we'll see.

Out of curiosity: was it prevented by github? There are no conflicts and it's a simple merge so if github prevents merging it from its web interface...

**Comment by robin92** [comment]
> Out of curiosity: was it prevented by github? There are no conflicts and it's a simple merge so if github prevents merging it from its web interface...

It's stange as I used to update branch from Web UI. I wonder what happened. In configuration everything seems to be all right though.

**Pull request merged**
